# Site settings
title: Paulo Henrique Raposo - Compositor
description: Portfólio # this means to ignore newlines until "baseurl:"
permalink: /:categories/:title:output_ext # adapted from TinyZz.github.io /:categories/:year/:month/:day/:title:output_ext
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://phraposo.github.io" # the base hostname & protocol for your site, e.g. http://example.com
logo: "/assets/img/branding/MVM-logo-full.svg"
logo-icon: "/assets/img/branding/MVM-symbol.svg"
logo-icon-SEO: "/assets/img/branding/MVM-symbol-black.png" # must be a non SVG file

# Night/Dark mode
# Default mode is "auto", "auto" is for auto nightshift
# (19:00 - 07:00), "manual" is for manual toggle, and
# "on/off" is for default on/off.
#
# Whatever the user's choice is, it will supersede the
# default setting of the site and be kept during the
# visit (session). Only the dark mode setting is "manual",
# it will be always kept on every visit (i.e. no matter
# the browser is closed or not)
night_mode: "auto"

logo-dark: "/assets/img/branding/MVM-logo-full-dark.svg"
highlight_theme: syntax-base16.monokai.dark # select a dark theme for the code highlighter if needed

# Author settings
author: Paulo Henrique Raposo # add your name
author-pic: Myself_Neon_grey.jpg
about-author: Músico, compositor, arranjador, guitarrista, violonista e desenvolvedor amador na área da composição assistida por computador, principalmente para o ambiente Openmusic.

# Contact links
email: paulohg.raposo@gmail.com # Add your Email address
#phone: # Add your Phone number
website: https://PHRaposo.github.io # Add your website
youtube: PauloHGRaposo
linkedin: paulo-henrique-raposo-25642982 # Add your Linkedin handle
github: PHRaposo # Add your Github handle
#twitter: '@MvmThe' # Add your Twitter handle
bandcamp: paulohenriqueraposo # Add your Bandcamp username
soundcloud: paulo-hg-raposo
#stackoverflow: stackoverflow # Add your stackoverflow account

# Newsletter
mailchimp: "https://b49990fe.sibforms.com/serve/MUIFAKgsaETUSjpctu5ToQd4jLOsdWqxHMcywP0qMQW023r0y-CSILRXzdJyE8H_W8wXbGhqYKoQgG81NfL0L33he2YrqlFBmWnab1Vk4bk4VV-JqkDTSW1PUEPeGFNxKiW362rX-OJhRyfR1FclVnEaM1cenNO4TKT26prqTWod48asPOwxzGqBb6hQ2ARKuyIsxT-W-L48IVNy" 
#"https://github.us1.list-manage.com/subscribe/post?u=8ece198b3eb260e6838461a60&amp;id=397d90b5f4"

# Tracker
analytics: G-R8SZS2YBZK
fbadmin: ar.maybach

# Paginate
paginate: 6
paginate_path: 'page:num'
words_per_minute: 200

extensions:
  mermaid_enable: true

# Comments
comments: #utteranc  #[disqus, utteranc]
comments_opts: 
comments_curtain: yes # leave empty to show the disqus embed directly
repo: # The GitHub repo URL.  https://utteranc.es/
issue_term: # The GitHub issue label
label: # The GitHub comments label
theme: #"preferred-color-scheme" # The GitHub comment's there. e.g. github-dark
#Disqus
discus_identifier: # Add your discus identifier

# Build settings
markdown: kramdown
mathjax: true
highlighter: rouge
compress_html:
  clippings: all
  comments: all
  startings: [html, head, body]

# Outputting
timezone: # America/Sao_Paulo -TEST https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

category_archive:
  type: liquid
  path: /categories/

sass:
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock", "package-lock.json", "assets/css/sass/"]


